### ISSUE TITLE
Image resize in KB or MB 

### ISSUE THREAD

**Issue by Chitranjan6G** [wkentaro/imgviz#45]
Will you add features to resize Image in KB or MB ?

And is possible to make image enhancer like https://letsenhance.io ?

**Comment by wkentaro** [comment]
- What is in KB or MB? (Is it the size of image like kilobytes? Then it already works)
- What image enhancement do you expect? If it is image super resolution with DNN, I don't think it's in the scope of this repo.

**Comment by Chitranjan6G** [comment]
Yes size in kilobytes.
But i didn't find in the documentation.

**Comment by wkentaro** [comment]
> Yes size in kilobytes.
But i didn't find in the documentation.
Can you help me to show?

Now I understood what you mean by resizing in KB or MB. You want to specify the data size (KB/MB) instead of pixel size to `imgviz.resize`, right? Then, it is not supported (probably will not be supported).

> Image inhancement, Low Quality image to high Quality image. will you add ?

Probably not. This repo is aiming at providing lightweight image visualization, and `image enhancement` and `image compression` are probably out of scope.

**Comment by wkentaro** [comment]
FYI, this looks useful for super resolution
https://github.com/alexjc/neural-enhance

**Comment by Chitranjan6G** [comment]
Ok, thank you
